# Generated by Django 3.0.5 on 2020-04-22 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionId', models.IntegerField(primary_key=True, serialize=False)),
                ('OwnerUserId', models.IntegerField()),
                ('Score', models.IntegerField()),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerId', models.IntegerField(primary_key=True, serialize=False)),
                ('Score', models.IntegerField()),
                ('IsAcceptedAnswer', models.BooleanField()),
                ('Body', models.TextField()),
                ('OwnerUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
                ('ParentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
