# Generated by Django 3.0.5 on 2020-04-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200423_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='IsAcceptedAnswer',
            field=models.BooleanField(default='False'),
        ),
    ]
