# Generated by Django 3.0.5 on 2020-04-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_score_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
