# Generated by Django 3.0.5 on 2020-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200430_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='QuestionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
